# Tugas Praktikum Pengolahan Citra Digital
## Implementasi Teknik Histogram dan Konvolusi

---

### **Soal 1: Perhitungan Manual Histogram Stretching**

**Deskripsi Soal:**
Buat matriks citra *grayscale* $4 \times 4$ dengan rentang nilai sempit (misalnya $80-120$), lakukan *histogram stretching* ke rentang penuh $0-255$ secara manual, dan sajikan langkah-langkah perhitungannya.

#### **1. Matriks Citra Asli ($I$) & Parameter**

Matriks citra *grayscale* ukuran $4 \times 4$ yang digunakan:

$$I = \begin{bmatrix} 
80 & 90 & 110 & 120 \\
90 & 110 & 115 & 90 \\
110 & 115 & 120 & 110 \\
115 & 120 & 80 & 90 
\end{bmatrix}$$

**Parameter Citra Asli:**
- **Nilai Intensitas Minimum ($r_{\min}$)** = $80$
- **Nilai Intensitas Maksimum ($r_{\max}$)** = $120$
- **Rentang Target ($S_{\min} \dots S_{\max}$)** = $0 \dots 255$ (Jumlah tingkat intensitas $L = 256$, sehingga $L-1 = 255$)

---

#### **2. Rumus Linear Histogram Stretching**

Rumus transformasi linier untuk merentangkan intensitas piksel $r$ menjadi $S$ adalah:

$$S = (L - 1) \times \frac{r - r_{\min}}{r_{\max} - r_{\min}}$$

Substitusi parameter ke dalam rumus:

$$S = 255 \times \frac{r - 80}{120 - 80} = 255 \times \frac{r - 80}{40}$$

---

#### **3. Langkah Perhitungan Manual Tiap Piksel ($r$)**

1. **Piksel $r = 80$:**
   $$S = 255 \times \frac{80 - 80}{40} = 255 \times 0 = 0$$

2. **Piksel $r = 90$:**
   $$S = 255 \times \frac{90 - 80}{40} = 255 \times \frac{10}{40} = 255 \times 0.25 = 63.75 \approx 64$$

3. **Piksel $r = 110$:**
   $$S = 255 \times \frac{110 - 80}{40} = 255 \times \frac{30}{40} = 255 \times 0.75 = 191.25 \approx 191$$

4. **Piksel $r = 115$:**
   $$S = 255 \times \frac{115 - 80}{40} = 255 \times \frac{35}{40} = 255 \times 0.875 = 223.125 \approx 223$$

5. **Piksel $r = 120$:**
   $$S = 255 \times \frac{120 - 80}{40} = 255 \times \frac{40}{40} = 255 \times 1 = 255$$

---

#### **4. Matriks Hasil Stretching ($S$)**

**a. Hasil Perhitungan Eksak (Nilai Desimal):**
$$S_{\text{eksak}} = \begin{bmatrix} 
0 & 63.75 & 191.25 & 255 \\
63.75 & 191.25 & 223.125 & 63.75 \\
191.25 & 223.125 & 255 & 191.25 \\
223.125 & 255 & 0 & 63.75 
\end{bmatrix}$$

**b. Hasil Pembulatan (Tipe Data `uint8` / $0-255$):**
$$S_{\text{uint8}} = \begin{bmatrix} 
0 & 64 & 191 & 255 \\
64 & 191 & 223 & 64 \\
191 & 223 & 255 & 191 \\
223 & 255 & 0 & 64 
\end{bmatrix}$$

**Kesimpulan:** Rentang intensitas citra yang semula sempit ($80 \dots 120$) berhasil direntangkan penuh ke rentang $0 \dots 255$ sehingga kontras citra meningkat secara signifikan.

In [1]:
import numpy as np

# 1. Matriks citra asli 4x4
I = np.array([
    [80, 90, 110, 120],
    [90, 110, 115, 90],
    [110, 115, 120, 110],
    [115, 120, 80, 90]
], dtype=np.uint8)

# 2. Parameter citra
r_min = I.min()
r_max = I.max()
L_minus_1 = 255

# 3. Perhitungan manual linier histogram stretching (sesuai rumus)
S_float = L_minus_1 * (I.astype(float) - r_min) / (r_max - r_min)
S_uint8 = np.round(S_float).astype(np.uint8)

# Display hasil
print("Matriks Asli (I):")
print(I)
print("\nHasil Stretching Eksak (Float):")
print(np.round(S_float, 3))
print("\nHasil Stretching Pembulatan (uint8):")
print(S_uint8)

Matriks Asli (I):
[[ 80  90 110 120]
 [ 90 110 115  90]
 [110 115 120 110]
 [115 120  80  90]]

Hasil Stretching Eksak (Float):
[[  0.     63.75  191.25  255.   ]
 [ 63.75  191.25  223.125  63.75 ]
 [191.25  223.125 255.    191.25 ]
 [223.125 255.      0.     63.75 ]]

Hasil Stretching Pembulatan (uint8):
[[  0  64 191 255]
 [ 64 191 223  64]
 [191 223 255 191]
 [223 255   0  64]]
